---
- name: Configure vms k8s
  become: true
  hosts:
    - proxmox
  gather_facts: false
  vars_files:
    - vault/proxmox_vars.yml
    - vars/main.yml
  tasks:
    - name: Gather ansible_default_ipv4 fact
      ansible.builtin.setup:
        filter: ansible_default_ipv4

    - name: Check the status of the vm k8s
      community.general.proxmox_kvm:
        api_host: "{{ ansible_default_ipv4.address }}"
        api_user: "{{ proxmox_user }}"
        api_token_id: "{{ proxmox_token_id }}"
        api_token_secret: "{{ proxmox_token_secret }}"
        vmid: "{{ item }}"
        state: started
        node: "{{ proxmox_node_name }}"
      register: vm_status
      loop: "{{ k8s_cluster_vms_baseid }}"
      loop_control:
        label: "VM ID {{ item }}"

    - name: Display VMs status
      ansible.builtin.debug:
        msg: |
          VM ID {{ item }}:
          - Status: {{ vm_status.results[loop.index0].status | default('Unknown') }}
          - Name: {{ vm_status.results[loop.index0].name | default('Unknown') }}
          - Node: {{ vm_status.results[loop.index0].node | default('Unknown') }}
      loop: "{{ k8s_cluster_vms_baseid }}"
